Repository pydata/sparse, pull requests merged in 2024-08, with the labels that each got.

#729 docs: Run python files under tutorials
  ci/test_examples.sh
  docs/examples/finch_example.py
  docs/examples/sparse_finch.ipynb
  examples/sparse_finch.ipynb
  mkdocs.yml
  pyproject.toml
Labels: documentation

#730 docs: Added `sparse.max` docstring
  docs/contributing.md
  mkdocs.yml
  sparse/numba_backend/_common.py
Labels: documentation

#733 ci: WIP Benchmarks
  .github/workflows/ci.yml
  .github/workflows/codespeed.yml
  benchmarks/test_benchmark_coo.py
  benchmarks_original/__init__.py
  benchmarks_original/benchmark_coo.py
  benchmarks_original/benchmark_gcxs.py
  benchmarks_original/benchmark_matmul.py
  benchmarks_original/benchmark_tensordot.py
  benchmarks_original/elemwise_example.py
  benchmarks_original/matmul_example.py
  benchmarks_original/mttkrp_example.py
  benchmarks_original/sddmm_example.py
  benchmarks_original/spmv_add_example.py
  benchmarks_original/utils.py
  ci/test_examples.sh
  pyproject.toml
Labels: internal

#736 ci: Template for bug reporting, upgrade python version for codspeed
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/codspeed.yml
Labels: internal

#737 ci: Correct template extension from `md` to `yml`
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: internal

#738 ci: Added more templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/doc_issue.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/question-support.md
  .github/ISSUE_TEMPLATE/question-support.yml
  .github/workflows/codspeed.yml
Labels: internal

#740 test: Benchmark to be run on codspeed
  benchmarks/test_benchmark_coo.py
Labels: internal

#741 test: Adapt benchmarks to use `codspeed`
  benchmarks/conftest.py
  benchmarks/test_benchmark_coo.py
  benchmarks/utils.py
Labels: internal

#743 test: Modified index and slice tests in order to vary ranks
  benchmarks/conftest.py
  benchmarks/test_benchmark_coo.py
Labels: internal

#742 depr, chore: Enforce deprecations and clean up warnings.
  examples/sparse_finch.ipynb
  sparse/__init__.py
  sparse/numba_backend/_common.py
  sparse/numba_backend/_coo/core.py
  sparse/numba_backend/_sparse_array.py
  sparse/numba_backend/_utils.py
  sparse/numba_backend/tests/test_coo.py
  sparse/tests/conftest.py
  sparse/tests/test_backends.py
Labels: deprecation

#747 fix: mkdocs Web after chore PR
  docs/_templates/autosummary/base.rst
  docs/_templates/autosummary/class.rst
  docs/_templates/autosummary/module.rst
  docs/api.md
  docs/index.md
  docs/operations.md
  docs/quickstart.md
  mkdocs.yml
Labels: fix

#748 test: Added gcxs to benchmarks to be tested with CodSpeed
  benchmarks/test_benchmark_coo.py
Labels: internal

#756 docs: Adding missing docstrings
  conftest.py
  sparse/numba_backend/_common.py
Labels: documentation

#749 test: Converting elemwise_example.py to CodSpeed benchmark
  benchmarks/test_elemwise.py
Labels: internal

#755 feat: MLIR backend POC
  .github/workflows/ci.yml
  conftest.py
  pyproject.toml
  sparse/__init__.py
  sparse/mlir_backend/__init__.py
  sparse/mlir_backend/_constructors.py
  sparse/mlir_backend/_core.py
  sparse/mlir_backend/_dtypes.py
  sparse/mlir_backend/_memref.py
  sparse/mlir_backend/_ops.py
  sparse/mlir_backend/tests/conftest.py
  sparse/mlir_backend/tests/test_simple.py
Labels: enhancement

#759 docs: Add example notebooks.
  .gitignore
  docs/css/mkdocstrings.css
  docs/examples/dask_example.py
  docs/examples/formats_example.py
  docs/examples/formats_example_finch.py
  docs/examples/scipy_example.py
  docs/javascripts/katex.js
  docs/js/katex.js
  mkdocs.yml
  pyproject.toml
Labels: documentation

#758 ci: Merge MLIR Backend
  .coveragerc
  .github/workflows/ci.yml
  ci/environment.yml
  sparse/mlir_backend/_core.py
  sparse/mlir_backend/tests/test_simple.py
Labels: internal

#757 feat, perf: Refactor the PoC to support multiple dtypes
  sparse/mlir_backend/_common.py
  sparse/mlir_backend/_constructors.py
  sparse/mlir_backend/_core.py
  sparse/mlir_backend/_dtypes.py
  sparse/mlir_backend/_memref.py
  sparse/mlir_backend/_ops.py
  sparse/mlir_backend/tests/conftest.py
  sparse/mlir_backend/tests/test_simple.py
Labels: enhancement

#761 test: Converting tensordot benchmark to run with CodSpeed
  benchmarks/test_tensordot.py
Labels: internal
