Repository pydata/sparse, pull requests merged in 2024-12, with the labels that each got.

#819 Introduce format factories
  ci/Finch-array-api-xfails.txt
  sparse/mlir_backend/__init__.py
  sparse/mlir_backend/_array.py
  sparse/mlir_backend/_conversions.py
  sparse/mlir_backend/_ops.py
  sparse/mlir_backend/formats.py
  sparse/mlir_backend/tests/test_simple.py
  sparse/numba_backend/_common.py
Labels: enhancement

#822 Allow no-copy construction from SciPy COO arrays.
  sparse/mlir_backend/_conversions.py
  sparse/mlir_backend/_dtypes.py
  sparse/mlir_backend/tests/test_simple.py
Labels: bug

#820 Update `sparse_finch` notebook and upgrade `finch-tensor`
  benchmarks_original/matmul_example.py
  benchmarks_original/mttkrp_example.py
  benchmarks_original/sddmm_example.py
  benchmarks_original/spmv_add_example.py
  ci/environment.yml
  examples/matmul_example.py
  examples/mttkrp_example.py
  examples/sddmm_example.py
  examples/sparse_finch.ipynb
  examples/spmv_add_example.py
  examples/triangles_example.py
  pixi.toml
  pyproject.toml
  sparse/finch_backend/__init__.py
  sparse/tests/test_backends.py
Labels: maintenance

#824 Remove workaround introduced in #822.
  pixi.toml
  sparse/mlir_backend/_conversions.py
Labels: maintenance

#827 Update `sparse_finch.ipynb`
  ci/environment.yml
  examples/sparse_finch.ipynb
  pixi.toml
  pyproject.toml
Labels: maintenance

#767 ci: Add doctests to CI again.
  .github/workflows/ci.yml
  .gitignore
  ci/environment.yml
  conftest.py
  pixi.lock
  pixi.toml
  pytest.ini
  sparse/mlir_backend/tests/__init__.py
  sparse/mlir_backend/tests/test_simple.py
  sparse/numba_backend/_common.py
  sparse/numba_backend/_compressed/compressed.py
  sparse/numba_backend/_coo/common.py
  sparse/numba_backend/_coo/core.py
  sparse/numba_backend/_coo/indexing.py
  sparse/numba_backend/_dok.py
  sparse/numba_backend/_sparse_array.py
  sparse/numba_backend/_utils.py
  sparse/numba_backend/tests/__init__.py
  sparse/numba_backend/tests/test_coo.py
  sparse/tests/__init__.py
Labels: internal
