Repository pydata/sparse, pull requests merged in 2024-10, with the labels that each got.

#784 ENH: Support 3D COO and cross-rank `reshape`
  sparse/mlir_backend/__init__.py
  sparse/mlir_backend/_common.py
  sparse/mlir_backend/_constructors.py
  sparse/mlir_backend/_ops.py
  sparse/mlir_backend/tests/test_simple.py
Labels: enhancement

#785 MAINT: Upgrade MLIR version
  ci/environment.yml
  pixi.toml
  sparse/mlir_backend/__init__.py
Labels: maintenance

#782 ENH: Implement `broadcast_to` function
  sparse/mlir_backend/__init__.py
  sparse/mlir_backend/_ops.py
  sparse/mlir_backend/tests/test_simple.py
Labels: enhancement

#791 ENH: Add `sparse_vector` constructor
  sparse/mlir_backend/_constructors.py
  sparse/mlir_backend/tests/test_simple.py
Labels: enhancement

#792 Format specification API
  pixi.toml
  sparse/mlir_backend/__init__.py
  sparse/mlir_backend/_array.py
  sparse/mlir_backend/_common.py
  sparse/mlir_backend/_constructors.py
  sparse/mlir_backend/_conversions.py
  sparse/mlir_backend/_dtypes.py
  sparse/mlir_backend/_ops.py
  sparse/mlir_backend/levels.py
  sparse/mlir_backend/tests/test_simple.py
Labels: enhancement, maintenance
