Repository pydata/sparse, pull requests merged in 2024-09, with the labels that each got.

#765 bld: Upgrade LLVM version to `19.1.0.rc3`
  ci/environment.yml
  sparse/mlir_backend/__init__.py
  sparse/mlir_backend/_constructors.py
  sparse/mlir_backend/_core.py
  sparse/mlir_backend/_ops.py
Labels: build

#771 MNT: Refactor MLIR constructors
  sparse/mlir_backend/_constructors.py
  sparse/mlir_backend/_core.py
  sparse/mlir_backend/_ops.py
  sparse/mlir_backend/tests/test_simple.py
Labels: maintenance

#777 docs: Convert README to markdown & add logo
  README.md
  README.rst
  docs/assets/images/logo_with_text.svg
Labels: documentation

#780 build: `pixi` environment setup
  .gitattributes
  .gitignore
  ci/environment.yml
  pixi.toml
  pyproject.toml
Labels: build

#781 ENH: Add counting triangles example
  examples/triangles_example.py
  pyproject.toml
Labels: enhancement
