Repository pydata/sparse, pull requests merged in 2024-11, with the labels that each got.

#808 Testing improvements and minor fixes.
  sparse/mlir_backend/__init__.py
  sparse/mlir_backend/_conversions.py
  sparse/mlir_backend/_ops.py
  sparse/mlir_backend/tests/test_simple.py
Labels: maintenance

#813 Attempt to fix Heisenbug by skipping COO.
  sparse/mlir_backend/tests/test_simple.py
Labels: bug

#805 BLD: Revert micromamba version to v2
  .github/workflows/ci.yml
Labels: build

#814 MAINT: Re-enable COO tests after fix
  sparse/mlir_backend/_conversions.py
  sparse/mlir_backend/tests/test_simple.py
Labels: maintenance
