Repository pydata/sparse, pull requests merged in 2024-07, with the labels that each got.

#716 MNT: Add CI mode to examples
  ci/test_examples.sh
  ci/test_notebooks.sh
  examples/elemwise_example.py
  examples/matmul_example.py
  examples/mttkrp_example.py
  examples/sddmm_example.py
  examples/spmv_add_example.py
  examples/utils.py
Labels: type:maintenance

#723 ci: Adding dependabot
  .github/dependabot.yml
Labels: internal

#725 docs: fixing cards links
  docs/examples.md
  docs/index.md
Labels: documentation

#726 docs: Fix how-to guides link on card
  docs/index.md
Labels: documentation

#728 ci: PR template, improved release-drafter
  .github/pull_request_template.md
  .github/release-drafter.yml
  docs/contributing.md
Labels: internal
