Repository pydata/sparse, pull requests merged in 2025-04, with the labels that each got.

#856 ENH: Import `moveaxis` in Finch backend
  ci/Finch-array-api-xfails.txt
  ci/environment.yml
  pixi.toml
  pyproject.toml
  sparse/finch_backend/__init__.py
Labels: enhancement

#857 MAINT: Use asterisk import for `finch-tensor`
  sparse/finch_backend/__init__.py
Labels: maintenance

#861 fix: Fix conversions from non-canonical `scipy.sparse` arrays
  sparse/numba_backend/_compressed/compressed.py
  sparse/numba_backend/_coo/core.py
  sparse/numba_backend/tests/test_conversion.py
Labels: fix
